"""Cross-layer scalar Green's function for layered soil (ADR-0007).

This module implements the electric (scalar-potential) Green's
function for a 2-layer soil where source and observer can be in
**either** layer. It complements the existing image-series solver in
:mod:`groundfield.solver.image_2layer` (which assumes both points in
the upper layer) and the Sommerfeld kernel in
:mod:`groundfield.solver.mom_sommerfeld` (same restriction).

Mathematical background
-----------------------
For a 2-layer soil with upper-layer resistivity $\\rho_1$ and
thickness $h_1$, lower-layer resistivity $\\rho_2$ semi-infinite,
the scalar Green's function for a unit point source at depth $z_s$
observed at depth $z$ takes the Hankel-transform form

$$
\\varphi(s, z, z_s) \\;=\\; \\int_0^{\\infty}\\!
\\Phi(\\lambda, z, z_s)\\,J_0(\\lambda s)\\,\\lambda\\,d\\lambda,
$$

where the spectral kernel $\\Phi(\\lambda, z, z_s)$ is determined by
the boundary-value problem

- $\\partial\\Phi/\\partial z = 0$ at $z = 0$ (free surface),
- $\\Phi$ continuous at $z = h_1$,
- $\\sigma_k\\,\\partial\\Phi/\\partial z$ continuous at $z = h_1$.

In each layer $\\Phi$ is a sum of $e^{\\pm\\lambda z}$ plus a
particular solution $e^{-\\lambda|z-z_s|}/(2\\lambda\\sigma_k)$ in
the layer that contains the source. The four layer-pair cases —
$\\Phi_{uu}, \\Phi_{ul}, \\Phi_{lu}, \\Phi_{ll}$ — correspond to
the four (source-layer, observer-layer) combinations and are
related by reciprocity ($\\Phi_{ul} = \\Phi_{lu}$).

Implementation
--------------
The 4×4 boundary-value system is solved numerically once per
$(\\lambda, z_s)$ pair (4 unknowns: amplitudes in each layer for
each direction). Per call the cost is dominated by $J_0$
evaluation and the linear solve at each $\\lambda$ node — fully
vectorisable with `numpy`.

The implementation focuses on the 2-layer case
(:class:`groundfield.soil.models.TwoLayerSoil`); the n-layer
extension follows the same recursion and is deferred to ADR-0007
Phase C.

Numerical strategy
------------------
The Hankel inversion is split into an analytic and a numerical
part, because the two halves of $\\Phi$ behave completely
differently in $\\lambda$:

1. **Primary term** — the particular solution
   $\\rho_k/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$ in the layer that
   contains the source. It does *not* decay when
   $|z - z_s| \\to 0$, and its Hankel inverse is known exactly,
   $\\rho_k/(2R)$ with $R = \\sqrt{s^2 + (z-z_s)^2}$. It is
   therefore evaluated in closed form
   (:func:`_primary_term_real_space`). Integrating it numerically
   instead — as versions up to 0.14.1 did — truncates at
   $\\lambda_\\text{max}$ and leaves an
   $O((\\lambda_\\text{max}R)^{-1/2})$ residue that *oscillates* in
   $s$ with period $2\\pi/\\lambda_\\text{max}$: up to 4.5 % on the
   total kernel, and non-monotone in ``lambda_max_factor``.
2. **Reflected remainder** — everything generated by the free
   surface and the interface. It is a superposition of image terms
   $c_j/(2\\lambda)\\,e^{-\\lambda d_j}$ (:func:`_image_generation`
   gives the exact coefficients and distances), so it decays like
   $e^{-\\lambda d_\\text{img}}$ with $d_\\text{img} = \\min_j d_j$
   the smallest image distance — but **only** in proportion to that
   distance. Every image distance can degenerate to zero
   ($z + z_s \\to 0$ for a surface pair, $|2h_1 - z - z_s| \\to 0$
   for a pair at the interface, $z_l - z_u \\to 0$ for a cross-layer
   pair straddling it), and then the remainder does not decay at all
   and truncating it is *not* safe. Versions up to 0.15.0.dev sized
   $\\lambda_\\text{max}$ from $\\min(h_1, s + z + z_s)$, which has no
   relation to $d_\\text{img}$, and were consequently wrong by 0.7 %
   … 40 % on such pairs with no warning (review pass 9 re-audit).
   Since 0.15.0 the truncation is *guaranteed*: every image term with
   $\\lambda_\\text{max} d_j < 30$ is subtracted from the spectral
   integrand and added back through its exact Hankel inverse
   $c_j/(2\\sqrt{s^2 + d_j^2})$
   (:func:`_reflected_image_terms`), so the numerically integrated
   rest provably decays like $e^{-\\lambda d_\\text{rest}}$ with
   $\\lambda_\\text{max} d_\\text{rest} \\ge 30$ and the discarded tail
   is bounded by $e^{-30} \\approx 10^{-13}$. The rest goes through
   the split-grid quadrature (:func:`_hankel_lambda_grid`):
   logarithmic nodes below the first $J_0$ oscillation, then one
   Gauss panel per oscillation period, with a documented resolution
   floor of eight nodes per period and a
   :class:`SommerfeldResolutionWarning` when the allocation budget
   cannot meet it.

Because the tail bound above is analytic, $\\lambda_\\text{max}$ no
longer has to be large — it only has to be *consistent* with the set
of subtracted image terms. That is what makes the cost of a remote
pair bounded: the node count of the oscillation-resolved grid grows
like $\\lambda_\\text{max}\\,s$, so the module caps
$\\lambda_\\text{max}$ at :data:`_HANKEL_PANEL_TARGET` panels (scaled
by ``lambda_max_factor / 200``) and subtracts as many image terms as
that cap requires (:func:`_plan_truncation`). A 4 km pair costs the
same as a 90 m one, and ``lambda_max_factor`` becomes a genuine
convergence knob: raising it moves work from the closed form into the
quadrature and *must not* change the answer.

Because the numerically integrated rest is analytic in
$t = \\ln(s + c)$ — and, after the image split above, has no scale
shorter than $d_\\text{rest}$, which is what $c$ is set to —
reaction blocks with many distance pairs at one $(z, z_s)$ are
evaluated on a range-sized log grid and cubic-spline interpolated
instead of pair by pair (~1e-6 relative, worst case 3e-5; see
:func:`two_layer_layered_correction_group`).

Limit checks (in the test suite)
--------------------------------
- $\\rho_2 = \\rho_1$: all four pair kernels reduce to the
  homogeneous Green's function $\\rho/(4\\pi r) + \\rho/(4\\pi r')$.
- $\\rho_2 \\to \\infty$ (PEC bottom): for source in upper layer,
  $G_{ul} \\to 0$ (no penetration into the lower layer);
  $G_{uu} \\to G_{uu}^{K \\to 1}$ — image structure with
  $K \\to 1$.
- $\\rho_2 \\to 0$ (sink): $G_{uu} \\to G_{uu}^{K \\to -1}$,
  spreading resistance drops dramatically.
- Source/observer in upper layer: bit-exact match to the
  Tagg/Sunde image series in
  :func:`groundfield.solver.image_2layer.solve_image_2layer`.

References
----------
- Sunde, E. D. (1968). *Earth Conduction Effects in Transmission
  Systems*, Dover, Ch. 3.
- Tagg, G. F. (1964). *Earth Resistances*, Newnes.
- Wait, J. R. (1972). *Electromagnetic Waves in Stratified Media*,
  Pergamon.
"""

from __future__ import annotations

import math
import warnings
from typing import NamedTuple

import numpy as np
from scipy.interpolate import CubicSpline
from scipy.special import j0
from functools import lru_cache


class SommerfeldResolutionWarning(UserWarning):
    """The Sommerfeld quadrature could not resolve the $J_0$ oscillations.

    The linear region of the Hankel grid places one Gauss panel per
    $J_0(\\lambda s)$ period, so the node count grows like
    $\\lambda_\\text{max}\\,s$. A hard node budget
    (:data:`_HANKEL_MAX_LINEAR_NODES`) bounds the transient allocation;
    when that budget forces fewer than
    :data:`_HANKEL_MIN_NODES_PER_OSCILLATION` nodes per period the
    quadrature is no longer converged and this warning is raised
    instead of returning a silently wrong number (a coarse grid on an
    oscillatory integrand does not merely lose digits — it can flip the
    sign of the result).

    The remedy is always to *lower* ``lambda_max_factor`` or to reduce
    the horizontal distance range of the group. Lowering the factor
    does **not** lose accuracy: the truncated tail is subtracted in
    closed form (:func:`_reflected_image_terms`), so a smaller
    $\\lambda_\\text{max}$ only moves work from the quadrature into the
    exact image sum. Silence with
    ``warnings.simplefilter("ignore", SommerfeldResolutionWarning)``
    only if the affected entries are known to be negligible.
    """


class SommerfeldTailTruncationWarning(UserWarning):
    """The $\\lambda$-truncated tail of the reflected kernel is not bounded.

    Sibling of :class:`SommerfeldResolutionWarning`: that one reports a
    grid too *coarse* to follow $J_0(\\lambda s)$, this one a grid too
    *short* to have integrated the reflected remainder.

    The reflected part of $\\Phi$ is a superposition of image terms
    $c_j/(2\\lambda)\\,e^{-\\lambda d_j}$, so truncating the Hankel
    integral at $\\lambda_\\text{max}$ discards
    $\\sum_j c_j/2 \\int_{\\lambda_\\text{max}}^\\infty e^{-\\lambda d_j}
    J_0(\\lambda s)\\,d\\lambda$, bounded by
    $\\sum_j |c_j| e^{-\\lambda_\\text{max} d_j}/(2 d_j)$. The bound is
    only small if $\\lambda_\\text{max} d_j$ is large for **every**
    retained term, and $d_j$ has nothing to do with the historic
    $\\lambda_\\text{max} = $ ``lambda_max_factor`` $/\\min(h_1, s + z +
    z_s)$: a pair at the air/soil surface ($z + z_s \\to 0$), at the
    layer interface ($|2h_1 - z - z_s| \\to 0$) or straddling it has
    $d_j \\to 0$ and a tail of order one. Review pass 9 measured
    −39.5 % on such a pair with *no* diagnostic; the failure grows as
    a mesh is refined towards the interface, which is what makes it
    release-blocking rather than cosmetic.

    Every term with $\\lambda_\\text{max} d_j <
    $ :data:`_HANKEL_TAIL_DECAY_TARGET` is therefore taken out of the
    quadrature and inverted in closed form. This warning fires when
    that could **not** be completed — in practice only when the term
    budget :data:`_HANKEL_IMAGE_TERM_BUDGET` is exhausted, which needs
    a very thin top layer, $|K| \\to 1$ and a multi-kilometre span at
    once. The result is then not bounded by the documented tolerance:
    lower ``lambda_max_factor`` (fewer image terms are needed), reduce
    the distance range, or raise the budget.
    """

# Peak-memory budget (bytes) for the dense ``J0(lambda * s)`` Bessel
# matrix that the Hankel contractions below would otherwise materialise
# in one shot. For a cross-layer grounding grid the number of distance
# pairs is ``n_seg**2`` and the oscillation-resolved lambda grid reaches
# ~5e4 nodes, so the full matrix can exceed 100 GiB. The contraction is
# blocked over the distance axis to keep the transient allocation below
# this budget; row-blocking a matmul is bit-for-bit identical to the
# single-shot form (see ``tests/test_layered_green_chunking.py``).
_HANKEL_MATMUL_BUDGET_BYTES = 512 * 1024 * 1024

# --- Oscillation resolution of the linear (large-lambda) region -------
#
# The linear region of the Hankel grid places one Gauss panel of order
# ``_HANKEL_PANEL_ORDER`` per J0 period ``2 pi / s``, so the node count
# grows like ``lambda_max * s``. The historic code clamped that at 4096
# panels with no accuracy check, which silently degraded to ~2.7 nodes
# per oscillation and flipped the sign of the result (review pass 9,
# finding F14). The resolution is now a *policy* with three tiers:
#
#   1. up to ``_HANKEL_SOFT_LINEAR_NODES`` (= the historic 4096 panels
#      x 16 nodes) the full one-panel-per-period target is used, so
#      every problem the historic cap handled stays bit-identical;
#   2. beyond that the panel count is only reduced down to the
#      ``_HANKEL_MIN_NODES_PER_OSCILLATION`` floor — the very same
#      8-nodes-per-oscillation adequacy criterion the single-panel fast
#      path below uses — so the node count keeps scaling with the
#      oscillation content instead of being clamped;
#   3. ``_HANKEL_MAX_LINEAR_NODES`` (1 Mi nodes ~= 75 MiB for the
#      (n_lambda, 3, 3) amplitude system) is a hard allocation budget.
#      If it forces fewer nodes per oscillation than the floor, a
#      :class:`SommerfeldResolutionWarning` is emitted rather than a
#      silently unconverged number.
_HANKEL_PANEL_ORDER = 16
_HANKEL_MIN_NODES_PER_OSCILLATION = 8.0
_HANKEL_SOFT_LINEAR_NODES = 1 << 16
_HANKEL_MAX_LINEAR_NODES = 1 << 20

# --- Truncation of the reflected tail (review pass 9 re-audit) --------
#
# The reflected kernel is the exact image superposition
# ``sum_j c_j/(2 lambda) exp(-lambda d_j)`` (see
# :func:`_image_generation`), so truncating the Hankel integral at
# ``lambda_max`` discards a tail bounded by
# ``sum_j |c_j| exp(-lambda_max d_j)/(2 d_j)``. ``lambda_max`` must
# therefore be sized against the *image distances*, not against
# ``min(h_1, s + z + z_s)``: every term is required to satisfy
# ``lambda_max * d_j >= _HANKEL_TAIL_DECAY_TARGET`` and every term that
# does not is subtracted from the integrand and added back through its
# exact Hankel inverse ``c_j/(2 sqrt(s^2 + d_j^2))``.
#
# ``exp(-30) = 9.4e-14``, i.e. ~9 orders below the module's documented
# 1e-4 kernel tolerance even after the ``s/d_j`` amplification of the
# bound relative to the term's own real-space size.
_HANKEL_TAIL_DECAY_TARGET = 30.0
# Once the split is in place there is no point integrating far beyond
# where the residual integrand has died: nodes spent there are nodes
# taken away from the region that carries the integral. ``lambda_max``
# is therefore also capped at ``MARGIN * TARGET / d_rest`` — a tail of
# ``exp(-120)``, i.e. every bit of margin one could want, while keeping
# the uniform panels of the linear region narrow enough to resolve
# ``exp(-lambda d_rest)``. Without this cap a large ``lambda_max_factor``
# put the whole integrand inside the first panel and *lost* accuracy
# (measured −4.4e-6 at factor 1000 for z = z_s = h_1, against −5e-10 at
# factor 300 — non-monotone in the public knob all over again).
_HANKEL_TAIL_DECAY_MARGIN = 4.0
# Terms below this fraction of ``max(rho)`` are left in the quadrature
# whatever their distance: they cannot matter at the module's tolerance
# (the image coefficients fall off like ``|K|^m``, so this is what
# terminates the term generation for a thin top layer).
_HANKEL_IMAGE_COEFF_FLOOR = 1e-17
# Hard cap on the number of closed-form image terms per (z, z_s) pair.
# Reaching it raises :class:`SommerfeldTailTruncationWarning`.
_HANKEL_IMAGE_TERM_BUDGET = 2048

# --- Cost policy for the oscillation-resolved grid --------------------
#
# The linear region carries one panel per J0 period, so its node count
# grows like ``lambda_max * s``. Because the discarded tail is bounded
# *analytically* (above) rather than by making ``lambda_max`` large,
# ``lambda_max`` may be lowered until the panel count fits this target,
# paying for it with a few more closed-form image terms. Without the
# cap a 4 km pair cost 42x a 90 m one (review pass 9 re-audit, item 3);
# with it the cost of a remote pair is bounded and, at the default
# knob, below v0.14.1 for every span beyond ~160 m.
#
# The target scales with ``lambda_max_factor / _HANKEL_PANEL_TARGET_AT``
# so that the public knob keeps its meaning: raising it really does
# raise ``lambda_max`` (and lower the number of closed-form terms),
# which is what makes a convergence check in that knob meaningful.
_HANKEL_PANEL_TARGET = 1024
_HANKEL_PANEL_TARGET_AT = 200.0

# --- Large-group interpolation policy ---------------------------------
#
# Above ``_HANKEL_INTERP_THRESHOLD`` distance pairs in one (z, z_s)
# group the *reflected* part of the kernel — smooth and analytic in the
# horizontal distance ``s`` because the singular primary 1/R term is
# split off in closed form (:func:`_primary_term_real_space`) — is
# sampled on a log-spaced ``s``-grid and interpolated by a not-a-knot
# cubic spline instead of being contracted at every pair. That turns
# whole-grid reaction blocks from O(n_pairs · n_lambda) into
# O(n_nodes · n_lambda), which is what makes a cross-layer grounding
# grid (n_pairs = n_seg**2) tractable in both time and memory.
#
# The node count is sized from the *actual* dynamic range of the group,
# ``t = log(s + c)`` spanning ``t_hi - t_lo``, at
# ``_HANKEL_INTERP_NODES_PER_LN`` nodes per e-fold (~28 per decade).
# A fixed node count (historically 48) meets its accuracy target only
# on the narrow ``s``-range it was tuned for and degrades to ~1 % over
# a 0…400 m network span. Interpolation is skipped whenever it would
# need at least as many nodes as there are pairs, so the switch at the
# threshold is not observable at the module's tolerance.
#
# Measured agreement between the two branches (0.15.0, ten geometries
# incl. surface, interface, near-interface and cross-layer pairs, spans
# up to 4 km, and every group size from 60 to 129 pairs): ~1e-6
# typical, worst case 1.1e-5. The worst case is a surface pair at
# ``s -> 0``, where the *scalar* branch is the less accurate of the two
# (the 32-node logarithmic region under-resolves a sharply decaying
# integrand there); against an independently derived closed form the
# interpolated branch is 4e-7 on that same geometry. Do not restate
# this as "~1e-8" — that claim was in the source at 0.15.0.dev and was
# 2–3 orders optimistic.
_HANKEL_INTERP_THRESHOLD = 64
_HANKEL_INTERP_NODES_PER_LN = 12.0
_HANKEL_INTERP_NODES_MIN = 48
_HANKEL_INTERP_NODES_MAX = 4096


def _hankel_contract(
    lambdas: np.ndarray, s_values: np.ndarray, w_phi: np.ndarray
) -> np.ndarray:
    """Blocked evaluation of ``J0(lambdas * s) @ w_phi`` over ``s``.

    Equivalent to ``j0(lambdas[None, :] * s_values[:, None]) @ w_phi``
    but never materialises the full ``(n_s, n_lambda)`` Bessel matrix:
    the distance axis is processed in row blocks sized so each transient
    ``J0`` block stays within :data:`_HANKEL_MATMUL_BUDGET_BYTES`. The
    result is identical to the single-shot contraction (a matmul is a
    row-independent reduction), so accuracy is unchanged; only peak
    memory is bounded. ``s_values`` of any shape is accepted and the
    original shape is preserved on return.
    """
    orig_shape = s_values.shape
    flat = np.ascontiguousarray(s_values, dtype=float).ravel()
    n_lambda = int(lambdas.shape[0])
    chunk = max(1, _HANKEL_MATMUL_BUDGET_BYTES // (8 * max(n_lambda, 1)))
    if flat.shape[0] <= chunk:
        return (j0(lambdas[None, :] * flat[:, None]) @ w_phi).reshape(orig_shape)
    out = np.empty(flat.shape[0], dtype=float)
    for a in range(0, flat.shape[0], chunk):
        b = a + chunk
        out[a:b] = j0(lambdas[None, :] * flat[a:b, None]) @ w_phi
    return out.reshape(orig_shape)


def _hankel_contract_smooth(
    lambdas: np.ndarray,
    s_values: np.ndarray,
    w_phi: np.ndarray,
    *,
    c: float,
) -> np.ndarray:
    """Contract a **smooth** Hankel weight over many distances.

    Mathematically identical to :func:`_hankel_contract`; the only
    difference is that for large groups the result is obtained from a
    cubic spline through log-spaced sample distances instead of one
    ``J0`` evaluation per pair. Admissible only for weights whose
    Hankel transform is analytic in ``s`` — i.e. after the singular
    primary term has been split off by
    :func:`_primary_term_real_space`.

    Parameters
    ----------
    lambdas, w_phi
        Quadrature nodes and the pre-multiplied weight
        ``Phi_reflected * weights * lambdas``.
    s_values
        Horizontal distances of the group, any shape.
    c
        Offset of the log coordinate $t = \\ln(s + c)$. Chosen as the
        vertical separation (floored at 1 mm) so that $t$ resolves both
        the plateau at $s \\ll |z - z_s|$ and the $1/s$ decay beyond.

    Returns
    -------
    np.ndarray
        Same shape as ``s_values``.
    """
    s_values = np.asarray(s_values, dtype=float)
    n_pairs = int(s_values.size)
    s_min = float(s_values.min())
    s_max = float(s_values.max())
    c = max(float(c), 1e-3)
    t_lo = math.log(s_min + c)
    t_hi = math.log(max(s_max + c, s_min + c + 1e-9))
    if t_hi - t_lo < 1e-9:
        # Degenerate group (all pairs at the same distance).
        value = float(_hankel_contract(lambdas, np.array([s_min]), w_phi)[0])
        return np.full(s_values.shape, value, dtype=float)
    n_nodes = _interp_node_count(t_lo, t_hi)
    if n_pairs <= _HANKEL_INTERP_THRESHOLD or n_nodes >= n_pairs:
        # Interpolation would cost at least as much as the exact
        # contraction — take the exact branch. This also keeps the step
        # at the threshold below the module's tolerance: the two
        # branches only ever meet where they agree to ~1e-6 (worst
        # measured 1.1e-5, see _HANKEL_INTERP_* above) — *not* to
        # ~1e-8, as this comment claimed at 0.15.0.dev.
        return _hankel_contract(lambdas, s_values, w_phi)
    t_nodes = np.linspace(t_lo, t_hi, n_nodes)
    s_nodes = np.maximum(np.exp(t_nodes) - c, 0.0)
    g_nodes = _hankel_contract(lambdas, s_nodes, w_phi)
    spline = CubicSpline(t_nodes, g_nodes)
    flat = spline(np.log(s_values.ravel() + c))
    return np.asarray(flat, dtype=float).reshape(s_values.shape)


@lru_cache(maxsize=None)
def _leggauss_cached(n: int):
    """Gauss-Legendre-Knoten/Gewichte fuer feste Ordnung ``n`` (gecacht).

    ``numpy.polynomial.legendre.leggauss`` loest je Aufruf ein
    Eigenwertproblem (O(n^3)). Im ADR-0007-Cross-Layer-Pfad wird die
    Quadratur pro Segmentpaar mit denselben festen Ordnungen
    (``n_log=32``, ``n_lin=96``) aufgerufen; ohne Cache dominiert der
    wiederholte Knotenaufbau die Laufzeit. Die Rueckgabe wird nur
    gelesen (keine In-place-Mutation), daher ist das Teilen sicher.
    """
    return np.polynomial.legendre.leggauss(n)


__all__ = [
    "SommerfeldResolutionWarning",
    "SommerfeldTailTruncationWarning",
    "two_layer_spectral_kernel",
    "two_layer_real_space_kernel",
    "two_layer_layered_correction_real_space",
    "two_layer_layered_correction_group",
    "two_layer_probe_matrix",
]


def _primary_term_real_space(
    rho: float,
    s: np.ndarray | float,
    dz: float,
    lambda_max: float,
) -> np.ndarray:
    """Closed form of the primary (source-layer particular) Hankel term.

    In the layer that contains the source the spectral kernel carries
    the particular solution $\\rho_k/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$
    whose Hankel inverse is known **exactly**:

    .. math::

       \\int_0^{\\infty}\\!\\frac{\\rho_k}{2\\lambda}\\,
       e^{-\\lambda |z-z_s|}\\,J_0(\\lambda s)\\,\\lambda\\,d\\lambda
       \\;=\\; \\frac{\\rho_k}{2\\,R},
       \\qquad R = \\sqrt{s^2 + (z-z_s)^2}.

    Why this matters numerically: that term is the only part of
    $\\Phi$ that does **not** decay exponentially in $\\lambda$ when
    $|z - z_s| \\to 0$. Truncating its quadrature at
    $\\lambda_\\text{max}$ leaves the slowly decaying, *oscillatory*
    remainder

    .. math::

       \\frac{\\rho_k}{2R}\\int_{\\lambda_\\text{max}R}^{\\infty}\\!
       J_0(u)\\,du \\;=\\; O\\!\\left(
       (\\lambda_\\text{max} R)^{-1/2}\\right),

    i.e. a few per cent at $\\lambda_\\text{max} R \\sim 10^2$ that
    oscillates in $s$ with period $2\\pi/\\lambda_\\text{max}$ — an
    error that does *not* shrink monotonically when the user raises
    ``lambda_max_factor``. Evaluating it in closed form and running the
    quadrature over the purely reflected remainder (which decays like
    $e^{-\\lambda\\,d_\\text{img}}$ with $d_\\text{img}$ the smallest
    image distance) removes both the magnitude and the spurious
    ``s``-oscillation, and is what makes the large-group interpolation
    below admissible.

    Parameters
    ----------
    rho
        Resistivity of the layer containing the source, in
        $\\Omega\\,\\mathrm{m}$.
    s
        Horizontal distance(s) in m (scalar or array).
    dz
        Vertical separation $z - z_s$ in m.
    lambda_max
        Upper truncation of the quadrature, in m⁻¹. The $1/R$ pole is
        clamped at $R = 1/\\lambda_\\text{max}$ — the finest length
        the companion quadrature can resolve — so the coincident-point
        limit stays finite and continuous exactly as in the historic
        all-quadrature form (whose value at $R = 0$ was
        $\\rho\\,\\lambda_\\text{max}/2$).

    Returns
    -------
    np.ndarray
        $\\rho/(2R)$, broadcast to the shape of ``s``.
    """
    R = np.hypot(np.asarray(s, dtype=float), float(dz))
    R = np.maximum(R, 1.0 / max(lambda_max, 1e-300))
    return 0.5 * rho / R


def _log_grid_offset(
    z: float, z_s: float, h_1: float, floor: float = 1e-3,
    *, d_rest: float = math.inf,
) -> float:
    """Offset $c$ of the interpolation coordinate $t = \\ln(s + c)$.

    The reflected kernel is a superposition of image potentials
    $1/\\sqrt{s^2 + d_n^2}$ whose vertical image distances $d_n$ are
    generated by the interface at $z = h_1$ and the free surface at
    $z = 0$: the two closest are $z + z_s$ (surface image of the
    source) and $|2h_1 - z - z_s|$ (first interface image); the
    cross-layer transmitted term contributes $|z - z_s|$. Every such
    term is *flat* for $s \\ll d_n$ and decays like $1/s$ for
    $s \\gg d_n$, so $t = \\ln(s + c)$ with $c$ equal to the **smallest**
    of those distances is the coordinate in which the whole
    superposition is uniformly smooth — one interpolation node per
    fixed $\\Delta t$ then resolves it everywhere.

    Choosing $c$ too small (the historic ``max(|z - z_s|, 1e-3)``
    collapsed to 1 mm for every equal-depth group) does not lose
    accuracy but wastes nodes: it spends e-folds of $t$ on the range
    $s < 1$ mm where the kernel is constant, which for a 400 m network
    span is roughly half of them.

    Parameters
    ----------
    z, z_s
        Observer / source depth in m.
    h_1
        Upper-layer thickness in m.
    floor
        Lower bound on the returned offset (the caller's near-field
        regularisation length). Prevents $c = 0$ when an image
        distance degenerates, e.g. $z = z_s = h_1$.
    d_rest
        Decay length of what actually goes through the interpolation,
        from :func:`_plan_truncation`. Since 0.15.0 every image term
        closer than ``30 / lambda_max`` — including the degenerate ones
        that used to drive this offset to its floor — is evaluated in
        closed form *outside* the interpolation, so the interpolated
        function has no scale shorter than ``d_rest`` and that, not the
        nearest image distance, is the correct offset. Left at
        ``inf`` the function reproduces the pre-0.15.0 choice, which is
        always a valid (merely node-wasting) lower bound.

    Returns
    -------
    float
        Offset $c > 0$ in m.
    """
    d_image = min(abs(z + z_s), abs(2.0 * h_1 - z - z_s))
    c = max(abs(z - z_s), d_image, floor)
    if math.isfinite(d_rest):
        c = max(c, d_rest)
    return c


def _interp_node_count(t_lo: float, t_hi: float) -> int:
    """Number of log-spaced interpolation nodes for a ``t``-range.

    The interpolated quantity is analytic in $t = \\ln(s + c)$, so the
    cubic-spline error scales like $(\\Delta t)^4$. Sizing the node
    count from the *actual* range at a fixed density
    (:data:`_HANKEL_INTERP_NODES_PER_LN` per e-fold) keeps $\\Delta t$
    — and hence the accuracy — independent of the network extent,
    which a fixed node count cannot do.
    """
    span = max(t_hi - t_lo, 0.0)
    n = int(math.ceil(_HANKEL_INTERP_NODES_PER_LN * span)) + 1
    return int(min(max(n, _HANKEL_INTERP_NODES_MIN), _HANKEL_INTERP_NODES_MAX))


def _validate_depths(
    z: float,
    z_s: float,
    labels: tuple[str, str] = ("z", "z_s"),
) -> None:
    """Reject depths above the air/soil interface.

    The boundary-value problem behind :func:`_spectral_amplitudes` is
    posed on $z \\ge 0$ (positive into the soil, free surface at
    $z = 0$). For $z < 0$ the "decaying" exponentials
    $e^{-\\lambda z}$ *grow*, the amplitude system overflows and the
    module returns ``nan`` — which propagates silently all the way to
    ``grounding_impedance()``. A module whose entire purpose is to
    never return a quietly wrong number must not return a quiet
    ``nan`` either, so negative depths raise instead.

    Known producer of negative depths (review pass 9 re-audit, item 4):
    the diagonal Gauss–Legendre averaging in
    :func:`groundfield.solver.image_2layer` forms
    ``z_lo = z_i - 0.5 * L_i``, which goes negative for a segment whose
    length exceeds twice its burial depth. That is a caller bug — the
    averaging interval must be clipped to the conductor — and it is
    reported separately; this check only makes it loud.
    """
    lz, lzs = labels
    if not (math.isfinite(z) and math.isfinite(z_s)):
        raise ValueError(
            f"layered_green: non-finite depths ({lz}={z!r}, "
            f"{lzs}={z_s!r}); the Hankel kernel is undefined there."
        )
    if z < 0.0 or z_s < 0.0:
        raise ValueError(
            f"layered_green: depths must be >= 0 (positive into the "
            f"soil, free surface at z = 0), got {lz}={z!r}, "
            f"{lzs}={z_s!r}. The two-layer boundary-value problem is "
            f"not posed above the air/soil interface and used to return "
            f"nan for such input. If these come from a segment-average "
            f"quadrature, clip the averaging interval to z >= 0."
        )


# =====================================================================
# Exact image expansion of the reflected kernel
# =====================================================================
def _image_generation(
    m: int,
    z: float,
    z_s: float,
    rho_1: float,
    rho_2: float,
    h_1: float,
    K: float,
) -> list[tuple[float, float]]:
    """Generation ``m`` of the exact image expansion of $\\Phi$.

    The reflected (non-particular) part of the spectral kernel is,
    exactly,

    .. math::

       \\Phi_\\text{refl}(\\lambda) \\;=\\;
       \\sum_j \\frac{c_j}{2\\lambda}\\,e^{-\\lambda d_j},

    obtained by expanding the $1/(1 - K e^{-2\\lambda h_1})$ resonance
    denominator of the closed-form solution of the matching problem in
    powers of $K e^{-2\\lambda h_1}$, $K = (\\rho_2 - \\rho_1) /
    (\\rho_2 + \\rho_1)$. Generation $m$ collects the terms carrying
    $K^m$; with $q = 2h_1$:

    - **both points in layer 1** ($z, z_s \\le h_1$), $S = z + z_s$,
      $D = |z - z_s|$: $m = 0$ contributes $(\\rho_1, S)$ — the free
      surface image — and $m \\ge 1$ contributes $\\rho_1 K^m$ at
      $mq + S$, $mq \\pm D$ and $mq - S$;
    - **both points in layer 2**: $m = 0$ contributes $(-\\rho_2 K,
      S - q)$ — the interface image, the one that degenerates when
      both points approach $h_1$ from below — and $(\\rho_2(1-K^2),
      S)$; $m \\ge 1$ contributes $\\rho_2(1-K^2)K^m$ at $S + mq$;
    - **cross-layer**, $z_u$ in layer 1 and $z_l$ in layer 2:
      $2\\rho_1\\rho_2/(\\rho_1+\\rho_2)\\,K^m$ at $mq + (z_l - z_u)$
      and $mq + (z_l + z_u)$. Note the first of these is the
      *transmitted direct* term: it degenerates for a pair straddling
      the interface, and it is the reason a cross-layer *correction*
      (which subtracts a homogeneous baseline that has its own
      $1/R$ direct term) is not automatically well truncated either.

    The real-space counterpart of each term is exactly
    $c_j / (2\\sqrt{s^2 + d_j^2})$, i.e. an image potential at vertical
    distance $d_j$ — which is what makes the closed-form split of
    :func:`_reflected_image_terms` possible.

    Coefficients are bounded by $2\\max(\\rho_1,\\rho_2)\\,|K|^m$, which
    is what terminates the expansion. Distances are *not* monotone in
    $m$ — the layer-1 case has $S$ at $m = 0$ and the much smaller
    $q - S$ at $m = 1$ — so a generator that walks generations must
    compare against :func:`_image_distance_floor`, the infimum over all
    generations from $m$ on, rather than against the current
    generation's own minimum. Getting that wrong silently skips exactly
    the degenerate interface term this machinery exists for.

    The expansion is verified against :func:`two_layer_spectral_kernel`
    node by node in ``tests/test_pass9_layered_green.py`` (agreement
    ~1e-15 relative once enough generations are summed) and, in the
    real-space direction, against the Tagg/Sunde series in
    ``tests/test_two_layer.py``'s reference geometries.
    """
    q = 2.0 * h_1
    Km = K ** m
    if z <= h_1 and z_s <= h_1:
        S = z + z_s
        D = abs(z - z_s)
        if m == 0:
            return [(rho_1, S)]
        c = rho_1 * Km
        return [
            (c, m * q + S),
            (c, m * q + D),
            (c, m * q - D),
            (c, m * q - S),
        ]
    if z > h_1 and z_s > h_1:
        S = z + z_s
        if m == 0:
            return [(-rho_2 * K, S - q), (rho_2 * (1.0 - K * K), S)]
        return [(rho_2 * (1.0 - K * K) * Km, S + m * q)]
    z_u, z_l = (z, z_s) if z <= h_1 else (z_s, z)
    c = 2.0 * rho_1 * rho_2 / (rho_1 + rho_2) * Km
    return [(c, m * q + (z_l - z_u)), (c, m * q + (z_l + z_u))]


def _image_distance_floor(
    m: int, z: float, z_s: float, h_1: float,
) -> float:
    """Smallest image distance in generations $m, m+1, \\dots$

    Used as the termination test of the walk in
    :func:`_reflected_image_terms`: once this exceeds the distance cut,
    no later generation can contribute a term that needs closed-form
    treatment, and the returned value *is* the decay length of what is
    left in the quadrature (it is attained by an actual term).

    The bookkeeping matters because the per-generation minimum is not
    monotone: for two points in layer 1 generation 0 sits at
    $S = z + z_s$ while generation 1 contains $2h_1 - S$, which is the
    degenerate interface image and can be arbitrarily small. Taking
    generation 0's own minimum as the bound skips it — and with it the
    entire point of the split (measured +4.1 % at $z = z_s = h_1$ before
    this was fixed).
    """
    q = 2.0 * h_1
    if z <= h_1 and z_s <= h_1:
        S = z + z_s
        if m == 0:
            return min(S, q - S)
        return m * q - S
    if z > h_1 and z_s > h_1:
        S = z + z_s
        if m == 0:
            return S - q
        return S + m * q
    z_u, z_l = (z, z_s) if z <= h_1 else (z_s, z)
    return m * q + (z_l - z_u)


class _TailSplit(NamedTuple):
    """Outcome of :func:`_plan_truncation`.

    Attributes
    ----------
    lambda_max
        Truncation of the Hankel quadrature actually used, in 1/m.
    lambda_clamp
        Regularisation wavenumber for the $1/R$ poles, ``1/lambda_clamp``
        being the shortest length the *requested* accuracy resolves. Kept
        separate from ``lambda_max`` so that the coincident-point value
        depends only on the user's knob and the depths, never on the
        largest ``s`` that happens to share the group.
    char_length
        Length scale of the log/linear split of the grid.
    coeffs, dists
        Image terms taken out of the quadrature and evaluated in closed
        form (possibly empty).
    d_rest
        Decay length of what is left for the quadrature: the smallest
        image distance still inside the integrand, ``inf`` if none is
        significant. Satisfies ``lambda_max * d_rest >=
        _HANKEL_TAIL_DECAY_TARGET`` unless the term budget was
        exhausted (which warns).
    """

    lambda_max: float
    lambda_clamp: float
    char_length: float
    coeffs: np.ndarray
    dists: np.ndarray
    d_rest: float


def _reflected_image_terms(
    z: float,
    z_s: float,
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
    rho_baseline: float | None,
    d_cut: float,
) -> tuple[np.ndarray, np.ndarray, float, bool]:
    """Image terms closer than ``d_cut``, and the decay of the rest.

    Walks :func:`_image_generation` until every remaining term is
    either farther than ``d_cut`` or below the coefficient floor, and
    splits the result into

    - the terms with $d_j <$ ``d_cut``, whose $\\lambda$-truncation
      would *not* be negligible and which the caller therefore removes
      from the integrand and adds back in closed form, and
    - ``d_rest``, the smallest distance among the terms left in the
      integrand — the decay length that ``lambda_max`` must be sized
      against.

    ``rho_baseline`` mirrors the public API: when it is not ``None`` the
    homogeneous baseline of that resistivity (the $K = 0$ generation) is
    appended with negated coefficients, so the same machinery serves the
    *correction* entry points. Terms at coincident distances are merged,
    which makes the common case ``rho_baseline == rho`` at the source
    cancel exactly instead of producing two closed-form terms that only
    cancel to rounding.

    Returns
    -------
    coeffs, dists : np.ndarray
        The closed-form terms, sorted by distance.
    d_rest : float
        Decay length of the remaining integrand (``inf`` if nothing
        significant is left).
    budget_exhausted : bool
        ``True`` if :data:`_HANKEL_IMAGE_TERM_BUDGET` stopped the walk
        before the distance cut was reached; the caller then warns.
    """
    K = (rho_2 - rho_1) / (rho_2 + rho_1)
    rho_b = 0.0 if rho_baseline is None else rho_baseline
    scale = 2.0 * max(rho_1, rho_2, rho_b)
    floor = _HANKEL_IMAGE_COEFF_FLOOR * scale
    raw: list[tuple[float, float]] = []
    d_next = math.inf
    budget_exhausted = False
    m = 0
    while True:
        if scale * abs(K) ** m <= floor:
            # Every remaining generation is below the coefficient floor:
            # leaving it in the quadrature cannot matter.
            break
        floor_m = _image_distance_floor(m, z, z_s, h_1)
        if floor_m > d_cut:
            # No generation from here on can contribute a closer term.
            d_next = floor_m
            break
        raw.extend(_image_generation(m, z, z_s, rho_1, rho_2, h_1, K))
        m += 1
        if len(raw) >= _HANKEL_IMAGE_TERM_BUDGET:
            budget_exhausted = True
            d_next = _image_distance_floor(m, z, z_s, h_1)
            break
    if rho_baseline is not None:
        for c, d in _image_generation(
            0, z, z_s, rho_baseline, rho_baseline, h_1, 0.0,
        ):
            raw.append((-c, d))

    merged: dict[float, float] = {}
    for c, d in raw:
        key = round(d, 12)
        merged[key] = merged.get(key, 0.0) + c
    near: list[tuple[float, float]] = []
    d_rest = d_next
    for d, c in merged.items():
        if abs(c) <= floor:
            continue
        if d < d_cut:
            near.append((d, c))
        else:
            d_rest = min(d_rest, d)
    near.sort()
    if not near:
        return (
            np.empty(0, dtype=float), np.empty(0, dtype=float),
            d_rest, budget_exhausted,
        )
    dists = np.array([d for d, _ in near], dtype=float)
    coeffs = np.array([c for _, c in near], dtype=float)
    return coeffs, dists, d_rest, budget_exhausted


def _image_spectral_sum(
    lambdas: np.ndarray, coeffs: np.ndarray, dists: np.ndarray,
) -> np.ndarray:
    """$\\sum_j c_j/(2\\lambda)\\,e^{-\\lambda d_j}$ on the grid."""
    if coeffs.size == 0:
        return np.zeros_like(lambdas)
    return (
        np.exp(-lambdas[:, None] * dists[None, :]) @ coeffs
    ) / (2.0 * lambdas)


def _image_real_space_sum(
    coeffs: np.ndarray,
    dists: np.ndarray,
    s: np.ndarray | float,
    lambda_clamp: float,
) -> np.ndarray | float:
    """$\\sum_j c_j/(2 R_j)$, the exact Hankel inverse of the above.

    $R_j = \\sqrt{s^2 + d_j^2}$, clamped at $1/\\lambda_\\text{clamp}$
    exactly like :func:`_primary_term_real_space` so that a coincident
    pair stays finite and the two closed-form pieces regularise
    consistently.
    """
    if coeffs.size == 0:
        return np.zeros_like(np.asarray(s, dtype=float))
    s_arr = np.asarray(s, dtype=float)
    R = np.hypot(s_arr[..., None], dists)
    R = np.maximum(R, 1.0 / max(lambda_clamp, 1e-300))
    return 0.5 * ((1.0 / R) @ coeffs)


def _plan_truncation(
    *,
    z: float,
    z_s: float,
    rho_1: float,
    rho_2: float,
    h_1: float,
    rho_baseline: float | None,
    s_near: float,
    s_far: float,
    lambda_max_factor: float,
    warn_stacklevel: int,
) -> _TailSplit:
    """Choose $\\lambda_\\text{max}$ *and* the closed-form image terms.

    The two decisions are one decision. Sizing $\\lambda_\\text{max}$
    from ``lambda_max_factor / min(h_1, s + z + z_s)`` — as every
    version up to 0.15.0.dev did — bounds nothing: the reflected
    integrand decays like $e^{-\\lambda d_\\text{img}}$ and
    $d_\\text{img}$ is unrelated to that expression, so the truncated
    tail was of order one whenever an image distance degenerated
    (surface pair, interface pair, cross-layer pair straddling the
    interface). Conversely, once every term with
    $\\lambda_\\text{max} d_j < $
    :data:`_HANKEL_TAIL_DECAY_TARGET` is subtracted and inverted in
    closed form, $\\lambda_\\text{max}$ may be chosen *freely* — the
    tail bound holds by construction — and is therefore chosen as small
    as the panel-cost target allows.

    Order of decisions:

    1. ``lambda_user = lambda_max_factor / char_length`` — the historic
       value, kept as the $1/R$ regularisation wavenumber
       (``lambda_clamp``) and as an upper bound on the truncation, so
       that nothing in the near field changes;
    2. cap it at :data:`_HANKEL_PANEL_TARGET` panels (scaled by
       ``lambda_max_factor / _HANKEL_PANEL_TARGET_AT``), which for the
       default knob binds only beyond $s \\approx 160$ m;
    3. subtract every image term closer than
       ``_HANKEL_TAIL_DECAY_TARGET / lambda_max``;
    4. lower ``lambda_max`` again to ``_HANKEL_TAIL_DECAY_MARGIN *
       _HANKEL_TAIL_DECAY_TARGET / d_rest`` if that is smaller — the
       residual integrand is ``exp(-120)`` there, and the uniform panels
       of the linear region resolve it far better than if they were
       stretched to a ``lambda_max`` the integrand never reaches;
    5. if the term budget stopped step 3 early, raise
       ``lambda_max`` back to what the closest retained term needs and
       warn (:class:`SommerfeldTailTruncationWarning`) — being slow or
       loud is acceptable, being quietly wrong is not.

    ``s_near`` (smallest radius of the group) sizes ``char_length`` and
    hence the knob; ``s_far`` (largest) sizes the oscillation cost.
    """
    char_length = max(min(h_1, s_near + z + z_s + 1e-9), 1e-3)
    lambda_user = lambda_max_factor / char_length
    lambda_max = lambda_user
    if s_far > 0.0:
        panels = min(
            _HANKEL_PANEL_TARGET * (
                lambda_max_factor / _HANKEL_PANEL_TARGET_AT
            ),
            # Never allocate more than the historic v0.14.1 cap. Beyond
            # this the knob saturates: pushing lambda_max further can
            # only run the grid into _HANKEL_MAX_LINEAR_NODES and out of
            # the eight-nodes-per-oscillation floor, which is a *worse*
            # answer than simply splitting off more image terms.
            float(_HANKEL_SOFT_LINEAR_NODES // _HANKEL_PANEL_ORDER),
        )
        lambda_cost = 2.0 * math.pi * max(panels, 1.0) / s_far
        lambda_max = min(lambda_max, lambda_cost)
    d_cut = _HANKEL_TAIL_DECAY_TARGET / lambda_max
    coeffs, dists, d_rest, exhausted = _reflected_image_terms(
        z, z_s, rho_1=rho_1, rho_2=rho_2, h_1=h_1,
        rho_baseline=rho_baseline, d_cut=d_cut,
    )
    if math.isfinite(d_rest) and d_rest > 0.0:
        lambda_max = min(
            lambda_max,
            _HANKEL_TAIL_DECAY_TARGET * _HANKEL_TAIL_DECAY_MARGIN / d_rest,
        )
    if d_rest * lambda_max < _HANKEL_TAIL_DECAY_TARGET:
        # Only reachable when the term budget was exhausted. Pay for the
        # tail with quadrature instead (the node-budget guard in
        # _hankel_lambda_grid then warns if even that is impossible).
        lambda_max = _HANKEL_TAIL_DECAY_TARGET / max(d_rest, 1e-300)
    if exhausted:
        lambda_needed = _HANKEL_TAIL_DECAY_TARGET / max(d_rest, 1e-300)
        warnings.warn(
            "layered_green: the reflected kernel needs more than "
            f"{_HANKEL_IMAGE_TERM_BUDGET} closed-form image terms to "
            f"bound its lambda-truncated tail at z = {z:.6g} m, "
            f"z_s = {z_s:.6g} m, h_1 = {h_1:.6g} m, s <= {s_far:.6g} m "
            f"(nearest retained image distance {d_rest:.3g} m needs "
            f"lambda_max >= {lambda_needed:.4g} "
            "1/m). The result is NOT bounded by the documented "
            "tolerance. Lower 'lambda_max_factor' (fewer image terms "
            "are then required), reduce the horizontal distance range, "
            "or raise '_HANKEL_IMAGE_TERM_BUDGET'.",
            SommerfeldTailTruncationWarning,
            stacklevel=warn_stacklevel,
        )
    return _TailSplit(
        lambda_max=lambda_max,
        lambda_clamp=lambda_user,
        char_length=char_length,
        coeffs=coeffs,
        dists=dists,
        d_rest=d_rest,
    )


def _spectral_amplitudes(
    lambdas: np.ndarray,
    z_s: float,
    rho_1: float,
    rho_2: float,
    h_1: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Solve the 2-layer matching for amplitudes at every $\\lambda$.

    Returns ``(a_1, b_1, a_2, b_2)`` such that the spectral kernel
    in each layer is

    - layer 1 ($0 \\le z \\le h_1$):
      $\\Phi_1(\\lambda, z) = a_1 e^{\\lambda z} + b_1 e^{-\\lambda z}
      + \\delta_{s\\in 1}\\,\\rho_1/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$,
    - layer 2 ($z > h_1$):
      $\\Phi_2(\\lambda, z) = a_2 e^{\\lambda z} + b_2 e^{-\\lambda z}
      + \\delta_{s\\in 2}\\,\\rho_2/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$.

    Numerical stability
    -------------------
    Direct use of $a_1 e^{\\lambda z}$ overflows for moderate
    $\\lambda h_1$ ($e^{200} \\approx 10^{86}$ already destroys
    the matrix conditioning). We therefore solve internally for
    the **stable amplitudes** $(A, B, C)$ via the change of
    variables

    .. math::

       a_1 = A\\,e^{-\\lambda h_1}, \\quad b_1 = B, \\quad
       b_2 = C\\,e^{-\\lambda h_1}.

    All coefficients in the resulting matrix are bounded by 1 in
    magnitude for any $\\lambda > 0$, so the linear solve is
    well-conditioned. The returned $(a_1, b_1, a_2, b_2)$ are then
    the unstable representation; callers that consume them must
    take care to use them only inside expressions where the
    growing exponential is multiplied by a decaying one (the
    spectral kernel evaluators in this module do exactly that).
    """
    # Source-in-which-layer flags
    source_in_upper = z_s <= h_1

    # Pre-compute the only exponential we need: e^{-λh_1} (bounded by 1).
    e_mlh = np.exp(-lambdas * h_1)

    # Source contribution coefficients at z=0 and z=h_1.
    if source_in_upper:
        # z_s in (0, h_1)
        # particular solution in layer 1: rho_1/(2λ) * exp(-λ|z - z_s|)
        # at z=0: ∂_z Φ_p|_{0} = +ρ_1/2 · exp(-λ z_s)
        dz_phi_p_0 = (rho_1 / 2.0) * np.exp(-lambdas * z_s)
        # at z=h_1: Φ_p(h_1) = ρ_1/(2λ) · exp(-λ(h_1 - z_s))
        phi_p_h = (rho_1 / (2.0 * lambdas)) * np.exp(-lambdas * (h_1 - z_s))
        # ∂_z Φ_p|_{h_1} = -ρ_1/2 · exp(-λ(h_1 - z_s))
        dz_phi_p_h = -(rho_1 / 2.0) * np.exp(-lambdas * (h_1 - z_s))
        phi_p_layer2_h = np.zeros_like(lambdas)
        dz_phi_p_layer2_h = np.zeros_like(lambdas)
    else:
        # z_s > h_1, source in layer 2
        dz_phi_p_0 = np.zeros_like(lambdas)
        phi_p_h = np.zeros_like(lambdas)
        dz_phi_p_h = np.zeros_like(lambdas)
        # at z=h_1: Φ_p(h_1) = ρ_2/(2λ) · exp(-λ(z_s - h_1))
        phi_p_layer2_h = (rho_2 / (2.0 * lambdas)) * np.exp(-lambdas * (z_s - h_1))
        # ∂_z Φ_p|_{h_1} = +ρ_2/2 · exp(-λ(z_s - h_1)) (since z_s > h_1)
        dz_phi_p_layer2_h = (rho_2 / 2.0) * np.exp(-lambdas * (z_s - h_1))

    # Solve the *stable* matrix system in (A, B, C) defined via
    #    a_1 = A·e^{-λh_1},   b_1 = B,   b_2 = C·e^{+λh_1}.
    #
    # The choice ``b_2 = C · e^{+λh_1}`` is essential for stability
    # in the lower layer: with it, the spectral kernel reads
    # ``Phi_2(z) = b_2·e^{-λz} = C·e^{-λ(z-h_1)}``, which is bounded
    # by ``|C|`` for any ``z ≥ h_1`` and any ``λ``. All exponentials
    # appearing in the matrix coefficients below are ``e^{-λh_1}``
    # (≤ 1) — no overflow even at the deepest λ in the quadrature.
    #
    # The original equations transform as follows:
    #
    # Eq 1 (∂_z Φ at z=0 = 0): λ a_1 - λ b_1 = -dz_phi_p_0
    #    ⇒ λ A·e^{-λh_1} - λ B = -dz_phi_p_0
    #
    # Eq 2 (continuity at z=h_1):
    #    a_1·e^{λh_1} + b_1·e^{-λh_1} + phi_p_h
    #      = b_2·e^{-λh_1} + phi_p_layer2_h
    #    ⇒ A + B·e^{-λh_1} - C = phi_p_layer2_h - phi_p_h
    #      (since a_1·e^{λh_1} = A and b_2·e^{-λh_1} = C·e^{λh_1}·e^{-λh_1} = C)
    #
    # Eq 3 (σ-weighted ∂_z continuity at z=h_1):
    #    σ_1·[λ a_1·e^{λh_1} - λ b_1·e^{-λh_1} + dz_phi_p_h]
    #      = σ_2·[-λ b_2·e^{-λh_1} + dz_phi_p_layer2_h]
    #    ⇒ σ_1·λ·A - σ_1·λ·B·e^{-λh_1} + σ_2·λ·C
    #      = σ_2·dz_phi_p_layer2_h - σ_1·dz_phi_p_h
    sigma_1 = 1.0 / rho_1
    sigma_2 = 1.0 / rho_2

    n = lambdas.size
    A_mat = np.zeros((n, 3, 3), dtype=float)
    rhs = np.zeros((n, 3), dtype=float)

    # Eq 1
    A_mat[:, 0, 0] = lambdas * e_mlh
    A_mat[:, 0, 1] = -lambdas
    A_mat[:, 0, 2] = 0.0
    rhs[:, 0] = -dz_phi_p_0

    # Eq 2
    A_mat[:, 1, 0] = 1.0
    A_mat[:, 1, 1] = e_mlh
    A_mat[:, 1, 2] = -1.0
    rhs[:, 1] = phi_p_layer2_h - phi_p_h

    # Eq 3
    A_mat[:, 2, 0] = sigma_1 * lambdas
    A_mat[:, 2, 1] = -sigma_1 * lambdas * e_mlh
    A_mat[:, 2, 2] = sigma_2 * lambdas
    rhs[:, 2] = sigma_2 * dz_phi_p_layer2_h - sigma_1 * dz_phi_p_h

    sol = np.linalg.solve(A_mat, rhs[..., None]).squeeze(-1)
    A = sol[:, 0]
    B = sol[:, 1]
    C = sol[:, 2]
    # Return the **stable** amplitudes (A, B, C). Callers should
    # use _phi_from_stable_amplitudes() to evaluate Phi(z) at any
    # observer depth without intermediate overflows.
    zeros = np.zeros_like(C)
    return A, B, zeros, C


def _phi_from_stable_amplitudes(
    lambdas: np.ndarray,
    A: np.ndarray, B: np.ndarray, C: np.ndarray,
    z: float, z_s: float,
    rho_1: float, rho_2: float, h_1: float,
    *,
    include_primary: bool = True,
) -> np.ndarray:
    """Evaluate $\\Phi(\\lambda, z, z_s)$ from the stable amplitudes.

    Builds the spectral kernel using **only** decaying exponentials
    so the result is bounded for any $\\lambda \\cdot h_1$.

    Decompositions:

    - layer 1 ($0 \\le z \\le h_1$):
      $\\Phi_1(\\lambda, z) = A\\,e^{-\\lambda(h_1-z)}
      + B\\,e^{-\\lambda z}
      + \\delta_{s\\in 1}\\,\\frac{\\rho_1}{2\\lambda}e^{-\\lambda|z-z_s|}$.
    - layer 2 ($z > h_1$):
      $\\Phi_2(\\lambda, z) = C\\,e^{-\\lambda(z-h_1)}
      + \\delta_{s\\in 2}\\,\\frac{\\rho_2}{2\\lambda}e^{-\\lambda|z-z_s|}$.

    Parameters
    ----------
    include_primary
        When ``False`` the particular (primary-source) term
        $\\rho_k/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$ is **omitted**,
        leaving only the reflected amplitudes. Callers that do this must
        add its closed-form real-space counterpart
        :func:`_primary_term_real_space` back after the Hankel
        inversion. The omitted term is the only part of $\\Phi$ that
        does not decay in $\\lambda$ *at all*; the remainder decays like
        $e^{-\\lambda d_\\text{img}}$, which is only fast enough to
        truncate if $\\lambda_\\text{max} d_\\text{img}$ is large — see
        :func:`_plan_truncation` for how that is enforced (it is not
        automatic: $d_\\text{img}$ degenerates for surface, interface
        and interface-straddling pairs).
    """
    if z <= h_1:
        Phi = (
            A * np.exp(-lambdas * (h_1 - z))
            + B * np.exp(-lambdas * z)
        )
        if z_s <= h_1 and include_primary:
            Phi = Phi + (rho_1 / (2.0 * lambdas)) * np.exp(
                -lambdas * abs(z - z_s)
            )
    else:
        Phi = C * np.exp(-lambdas * (z - h_1))
        if z_s > h_1 and include_primary:
            Phi = Phi + (rho_2 / (2.0 * lambdas)) * np.exp(
                -lambdas * abs(z - z_s)
            )
    return Phi


def _primary_rho(
    z: float, z_s: float, rho_1: float, rho_2: float, h_1: float,
) -> float:
    """Resistivity multiplying the primary $1/R$ term, 0 across layers.

    The particular solution lives only in the layer that contains the
    source and only contributes to the observer's own layer, so the
    primary $1/R$ field is present exactly when both points are on the
    same side of $z = h_1$ (the cross-layer kernels $\\Phi_{ul}$,
    $\\Phi_{lu}$ are purely reflected and decay like
    $e^{-\\lambda\\,d_\\text{img}}$).
    """
    if (z <= h_1) != (z_s <= h_1):
        return 0.0
    return rho_1 if z_s <= h_1 else rho_2


def two_layer_spectral_kernel(
    lambdas: np.ndarray,
    z: float,
    z_s: float,
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
) -> np.ndarray:
    """Spectral Green's function $\\Phi(\\lambda, z, z_s)$.

    Returns the value of the spectral kernel at every $\\lambda$
    in ``lambdas`` for given source depth $z_s$ and observer depth
    $z$. Both depths can be in either layer.

    Parameters
    ----------
    lambdas
        1-D array of spectral variable values, $\\lambda > 0$ in
        units of m⁻¹.
    z, z_s
        Observer / source depth in metres ($z \\ge 0$, positive into
        the soil).
    rho_1, rho_2
        Resistivities of upper / lower layer in $\\Omega\\,\\mathrm{m}$.
    h_1
        Upper-layer thickness in m.

    Returns
    -------
    Phi : np.ndarray, shape (n_lambda,)
    """
    A, B, _, C = _spectral_amplitudes(
        lambdas, z_s, rho_1, rho_2, h_1,
    )
    return _phi_from_stable_amplitudes(
        lambdas, A, B, C, z, z_s, rho_1, rho_2, h_1,
    )


def _hankel_lambda_grid(
    *,
    lambda_max: float,
    char_length: float,
    s: float,
    n_log: int,
    n_lin: int,
    warn_stacklevel: int = 3,
) -> tuple[np.ndarray, np.ndarray]:
    """Quadrature grid for the semi-infinite Hankel integrals.

    Log-spaced Gauss nodes on $[\\epsilon, \\lambda_\\text{break}]$
    plus a linear region $[\\lambda_\\text{break},
    \\lambda_\\text{max}]$ that **resolves the $J_0(\\lambda s)$
    oscillations** (audit 2026-07-08, finding N1): the historic
    single ``n_lin``-node panel under-integrated the tail for
    $s \\gg \\min(h_1, \\text{depths})$ — measured errors of 2.5 %
    at $s = 100$ m and 46 % at $s = 200$ m for cross-layer pairs.

    Strategy: when the linear region carries at most ``n_lin / 8``
    oscillations, the historic single panel is kept (bit-exact with
    pre-audit results). Beyond that, the region is split into one
    ``_HANKEL_PANEL_ORDER``-node Gauss panel per oscillation period
    $2\\pi/s$, so the node count **scales with the oscillation content**
    $n_\\text{osc} = (\\lambda_\\text{max} -
    \\lambda_\\text{break})\\,s / 2\\pi$ of the requested integration
    range.

    Resolution guarantee (review pass 9, finding F14)
    -------------------------------------------------
    The historic hard cap of 4096 panels was an *accuracy* policy
    disguised as a memory limit: it silently degraded to ~2.7 nodes per
    oscillation once $n_\\text{osc} \\gtrsim 4\\cdot 10^3$, which is
    reached by a 200 m pair at ``lambda_max_factor = 6000`` and by a
    6 km pair at the default factor. On an oscillatory integrand a
    coarse grid does not merely lose digits — the measured layered
    correction changed sign (−0.2311 → +0.0349, 115 % error) while the
    user was *raising* the documented accuracy knob.

    The panel count now keeps scaling with $n_\\text{osc}$, reduced at
    most to the :data:`_HANKEL_MIN_NODES_PER_OSCILLATION` floor once the
    soft node budget :data:`_HANKEL_SOFT_LINEAR_NODES` (numerically
    equal to the historic 4096 × 16 nodes) is exceeded, so every grid
    the historic cap resolved adequately is reproduced **bit for bit**
    while $n_\\text{osc} > 8192$ no longer degrades. Only the hard
    allocation budget :data:`_HANKEL_MAX_LINEAR_NODES` can still force
    fewer nodes per period than the floor, and that case raises a
    :class:`SommerfeldResolutionWarning` naming ``lambda_max_factor``
    instead of returning a silently wrong number.

    Parameters
    ----------
    lambda_max
        Truncation of the integral, in 1/m. Chosen by
        :func:`_plan_truncation` — **not** simply
        ``lambda_max_factor / char_length`` — because the discarded tail
        is bounded by the closed-form image split rather than by making
        ``lambda_max`` large, which lets the panel cost be capped.
    char_length
        Length scale of the log/linear break point only.
    s
        Radius whose $J_0(\\lambda s)$ oscillations must be resolved
        (the largest of a group).
    warn_stacklevel
        Frames between this function and the user's call site, so the
        warning points at user code for every public entry point (3 for
        the three direct ones, 4 for :func:`two_layer_probe_matrix`,
        which goes through a nested helper). Getting this wrong also
        mis-keys the default once-per-location warning de-duplication.

    Returns
    -------
    lambdas, weights : np.ndarray
        Concatenated nodes and weights of both regions.

    Warns
    -----
    SommerfeldResolutionWarning
        If the node budget prevents resolving the $J_0$ oscillations.

    Note
    ----
    :func:`groundfield.coupling.sommerfeld_inductance._build_lambda_grid`
    still carries the historic unchecked 4096-panel cap (with 8-node
    panels); it is not touched here.
    """
    lambda_break = max(min(1.0 / char_length, 0.5 * lambda_max), 1e-9)
    # The log region must stay oscillation-free: cap lambda_break at
    # 1/8 of the first J0 period so that all Bessel oscillations fall
    # into the (oscillation-resolved) linear region. For small s the
    # cap is inactive and the historic break point is kept bit-exact.
    if s > 0.0:
        lambda_break = max(
            min(lambda_break, 0.25 * math.pi / s), 1e-9,
        )

    # Logarithmic part [eps, lambda_break] — unchanged.
    nodes_log_x, weights_log_x = _leggauss_cached(n_log)
    eps = max(lambda_max * 1e-12, 1e-15)
    a_log = math.log(eps)
    b_log = math.log(lambda_break)
    t = 0.5 * (nodes_log_x + 1.0) * (b_log - a_log) + a_log
    lambdas_log = np.exp(t)
    weights_log = 0.5 * weights_log_x * (b_log - a_log) * lambdas_log

    # Linear part [lambda_break, lambda_max].
    n_osc = (lambda_max - lambda_break) * s / (2.0 * math.pi)
    if 8.0 * n_osc <= float(n_lin):
        # Historic single panel — >= 8 nodes per oscillation.
        nodes_lin_x, weights_lin_x = _leggauss_cached(n_lin)
        half = 0.5 * (lambda_max - lambda_break)
        lambdas_lin = half * (nodes_lin_x + 1.0) + lambda_break
        weights_lin = half * weights_lin_x
    else:
        # Tier 1: one panel per oscillation (16 nodes/oscillation).
        n_panels_target = int(math.ceil(n_osc))
        # Tier 2: the 8-nodes-per-oscillation adequacy floor.
        n_panels_floor = int(math.ceil(
            n_osc * _HANKEL_MIN_NODES_PER_OSCILLATION / _HANKEL_PANEL_ORDER
        ))
        order = _HANKEL_PANEL_ORDER
        n_panels_soft = max(1, _HANKEL_SOFT_LINEAR_NODES // order)
        n_panels_hard = max(1, _HANKEL_MAX_LINEAR_NODES // order)
        n_panels = min(
            n_panels_target, max(n_panels_soft, n_panels_floor), n_panels_hard,
        )
        nodes_per_osc = _HANKEL_PANEL_ORDER * n_panels / n_osc
        if nodes_per_osc < _HANKEL_MIN_NODES_PER_OSCILLATION:
            warnings.warn(
                "layered_green: Hankel quadrature cannot resolve the "
                f"J0 oscillations — {n_osc:.3g} oscillations over "
                f"[{lambda_break:.3g}, {lambda_max:.3g}] 1/m at "
                f"s = {s:.4g} m need at least {n_panels_floor} panels "
                f"but the node budget allows {n_panels_hard} "
                f"({nodes_per_osc:.2f} nodes per oscillation < "
                f"{_HANKEL_MIN_NODES_PER_OSCILLATION:.0f}). The result "
                "is NOT converged and may have the wrong sign. Lower "
                "'lambda_max_factor' — accuracy does not depend on it "
                "(the truncated tail is subtracted in closed form, see "
                "_plan_truncation), only the split between quadrature "
                "and closed form does — or reduce the horizontal "
                "distance range.",
                SommerfeldResolutionWarning,
                stacklevel=warn_stacklevel,
            )
        edges = np.linspace(lambda_break, lambda_max, n_panels + 1)
        nodes_p, weights_p = _leggauss_cached(_HANKEL_PANEL_ORDER)
        half_w = 0.5 * np.diff(edges)                       # (n_panels,)
        centers = 0.5 * (edges[:-1] + edges[1:])            # (n_panels,)
        lambdas_lin = (
            centers[:, None] + half_w[:, None] * nodes_p[None, :]
        ).ravel()
        weights_lin = (half_w[:, None] * weights_p[None, :]).ravel()

    lambdas = np.concatenate([lambdas_log, lambdas_lin])
    weights = np.concatenate([weights_log, weights_lin])
    return lambdas, weights


def two_layer_real_space_kernel(
    s: float,
    z: float,
    z_s: float,
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
    lambda_max_factor: float = 200.0,
    n_log: int = 32,
    n_lin: int = 96,
) -> float:
    """Cross-layer real-space scalar Green's function $\\varphi(s, z, z_s)$.

    Computes $\\varphi(s, z, z_s) / I = \\int_0^\\infty
    \\Phi(\\lambda, z, z_s)\\,J_0(\\lambda s)\\,\\lambda\\,d\\lambda$
    for a unit point source at $(0, 0, z_s)$ observed at $(s, 0, z)$.
    The result already includes the $1/(4\\pi)$-style prefactor that
    is conventional in the existing `mom_sommerfeld` kernel
    representation.

    Numerical strategy: the primary (source-layer particular) term is
    evaluated in **closed form** as $\\rho_k/(2R)$ with
    $R = \\sqrt{s^2 + (z-z_s)^2}$
    (:func:`_primary_term_real_space`), and so is every reflected image
    term whose distance is too short for the truncation at
    $\\lambda_\\text{max}$ to be negligible
    (:func:`_reflected_image_terms`, :func:`_plan_truncation`); only the
    provably fast-decaying rest goes through the split-grid Sommerfeld
    quadrature (logarithmic for small $\\lambda$, oscillation-resolved
    for large $\\lambda$) consistent with
    :mod:`groundfield.coupling.sommerfeld_inductance` (ADR-0006).

    Measured against an independently derived closed form (image
    expansion summed to convergence): ~3e-10 relative for surface
    pairs, interface pairs, pairs a millimetre below the interface,
    cross-layer pairs straddling it, and radii from 0 to 20 km — and
    *identical to ten digits* for ``lambda_max_factor`` anywhere in
    30 … 30 000. Up to 0.15.0.dev the same geometries were wrong by
    0.7 % … 40 % with no warning, and non-monotone in the knob.

    Splitting the primary term off matters because it is the only part
    of $\\Phi$ that does not decay in $\\lambda$: integrating it
    numerically up to $\\lambda_\\text{max}$ left an
    $O((\\lambda_\\text{max}R)^{-1/2})$ oscillatory residue — measured
    −4.5 % at $s = 1$ m and ±4 % swings with period
    $2\\pi/\\lambda_\\text{max} \\approx 0.03$ m for equal-depth pairs,
    and *non-monotone* in ``lambda_max_factor``. In the homogeneous
    limit $\\rho_2 = \\rho_1$ the closed form now reproduces
    $\\rho/2\\,(1/r + 1/r')$ to ~1e-13 instead of ~1e-2.

    For ``s = 0`` and ``z = z_s`` every $1/R$ pole is clamped at
    $R = 1/\\lambda_\\text{clamp}$ with $\\lambda_\\text{clamp} =$
    ``lambda_max_factor`` $/\\min(h_1, s + z + z_s)$ — so the return
    value stays finite and continuous and depends only on the knob and
    the depths, but it is *not* a physical potential: the caller must
    regularise at the wire radius.

    Parameters
    ----------
    s : float
        Cylindrical radius in m, $\\ge 0$.
    z, z_s : float
        Observer / source depths in m, $\\ge 0$ (positive into the
        soil). Negative depths raise :class:`ValueError` — they used to
        return ``nan``.
    rho_1, rho_2, h_1 : float
        Two-layer soil parameters.
    lambda_max_factor
        *Upper bound* on the quadrature truncation, as a multiple of
        $1/\\bar h$ with $\\bar h = \\min(h_1, s + z + z_s)$, and the
        regularisation wavenumber of the $1/R$ poles. It is **not** the
        truncation actually used: since 0.15.0 the truncated tail is
        bounded by a closed-form image split rather than by making
        $\\lambda_\\text{max}$ large, so $\\lambda_\\text{max}$ is
        lowered to whatever that split allows
        (:func:`_plan_truncation`). Consequence: raising this knob is
        normally a no-op and *cannot* change the answer, which is the
        whole point — review pass 9 found the result flipping sign as it
        was raised. Lowering it below ~30/(smallest image distance)
        still moves work into the closed form and must likewise leave
        the answer unchanged; that is the convergence check to run.
    n_log, n_lin
        Number of nodes in the logarithmic / linear part of the
        quadrature grid.

    Returns
    -------
    G : float
        Real-space scalar Green's function (dimensionless after
        dividing by $\\rho$).
    """
    _validate_depths(z, z_s)
    plan = _plan_truncation(
        z=z, z_s=z_s, rho_1=rho_1, rho_2=rho_2, h_1=h_1,
        rho_baseline=None, s_near=s, s_far=s,
        lambda_max_factor=lambda_max_factor, warn_stacklevel=3,
    )
    lambdas, weights = _hankel_lambda_grid(
        lambda_max=plan.lambda_max, char_length=plan.char_length, s=s,
        n_log=n_log, n_lin=n_lin, warn_stacklevel=3,
    )

    A, B, _, C = _spectral_amplitudes(lambdas, z_s, rho_1, rho_2, h_1)
    Phi_refl = _phi_from_stable_amplitudes(
        lambdas, A, B, C, z, z_s, rho_1, rho_2, h_1,
        include_primary=False,
    ) - _image_spectral_sum(lambdas, plan.coeffs, plan.dists)
    integrand = Phi_refl * j0(lambdas * s) * lambdas
    total = float(np.sum(weights * integrand))
    total += float(
        _image_real_space_sum(plan.coeffs, plan.dists, s, plan.lambda_clamp)
    )

    rho_primary = _primary_rho(z, z_s, rho_1, rho_2, h_1)
    if rho_primary == 0.0:
        return total
    return total + float(
        _primary_term_real_space(rho_primary, s, z - z_s, plan.lambda_clamp)
    )


def two_layer_layered_correction_group(
    s_values: np.ndarray,
    z: float,
    z_s: float,
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
    rho_baseline: float | None = None,
    lambda_max_factor: float = 200.0,
    n_log: int = 32,
    n_lin: int = 96,
) -> np.ndarray:
    """Vectorised form of :func:`two_layer_layered_correction_real_space`.

    Evaluates the layered correction for **many horizontal distances
    at one (z, z_s) pair** with a single spectral-amplitude solve:
    the amplitudes depend on (λ, z, z_s) only, so the per-pair cost
    of the historic scalar loop (one BVP solve per matrix entry —
    the dominant cost of the ADR-0007 cross-layer reaction-matrix
    assembly after the WP-B1 oscillation-resolved grids) collapses
    to one BVP solve per (z, z_s) group plus a ``J0`` contraction.

    The shared λ-grid is built for the most demanding radius of the
    group: the ``lambda_max_factor`` bound and the $1/R$ regularisation
    from the smallest ``s`` (near-field content), oscillation
    resolution, log-region cap and panel-cost budget from the largest
    (:func:`_plan_truncation`).

    Accuracy (review pass 9, finding F15)
    -------------------------------------
    Groups above :data:`_HANKEL_INTERP_THRESHOLD` pairs are sampled on
    a log-spaced ``s``-grid and interpolated. Three changes make that
    branch agree with the exact per-pair contraction to ~1e-6 relative
    (worst case measured 1.1e-5, over ten geometries and every group
    size from 60 to 129 pairs; previously up to 1 % for a 400 m span
    and 17 % when ``rho_baseline`` did not match the source layer):

    1. the residual primary term
       $(\\rho_\\text{src} - \\rho_\\text{baseline})/(2\\lambda)\\,
       e^{-\\lambda|z-z_s|}$ — which is *not* zero unless the caller
       matches ``rho_baseline`` to the source layer, and which carries a
       $1/R$ singularity plus a $2\\pi/\\lambda_\\text{max}$-periodic
       truncation ripple in ``s`` — is taken out of the quadrature and
       added back in closed form, leaving a genuinely analytic
       integrand;
    2. the node count is sized from the actual dynamic range of the
       group and the interpolant is a cubic spline, so the accuracy no
       longer depends on the network extent;
    3. every reflected image term short enough for the λ-truncation to
       matter gets the same treatment as the primary term — closed form,
       per pair, outside the interpolation
       (:func:`_reflected_image_terms`). This is what removes the
       0.7 % … 40 % errors of surface, interface and interface-straddling
       pairs, and it also *smooths* what remains: the interpolated
       function then has no length scale shorter than ``d_rest``, which
       is what the log-coordinate offset is set to.

    Because interpolation is skipped whenever it would need at least as
    many nodes as the group has pairs, the exact and the interpolated
    branch also no longer differ observably at the threshold (the
    historic ~3 % jump between a 64-pair and a 65-pair block is gone;
    worst deviation over every size from 60 to 129 pairs is 1.1e-5).
    """
    if rho_baseline is None:
        rho_baseline = rho_1
    _validate_depths(z, z_s)
    s_values = np.asarray(s_values, dtype=float)
    if abs(rho_2 - rho_1) < 1e-12 * max(rho_1, 1.0) and \
            abs(rho_baseline - rho_1) < 1e-12 * max(rho_1, 1.0):
        return np.zeros(s_values.shape, dtype=float)
    s_min = float(s_values.min())
    s_max = float(s_values.max())
    plan = _plan_truncation(
        z=z, z_s=z_s, rho_1=rho_1, rho_2=rho_2, h_1=h_1,
        rho_baseline=rho_baseline, s_near=s_min, s_far=s_max,
        lambda_max_factor=lambda_max_factor, warn_stacklevel=3,
    )
    lambdas, weights = _hankel_lambda_grid(
        lambda_max=plan.lambda_max, char_length=plan.char_length, s=s_max,
        n_log=n_log, n_lin=n_lin, warn_stacklevel=3,
    )
    A, B, _, C = _spectral_amplitudes(lambdas, z_s, rho_1, rho_2, h_1)
    A_h, B_h, _, C_h = _spectral_amplitudes(
        lambdas, z_s, rho_baseline, rho_baseline, h_1,
    )
    Phi_lay = _phi_from_stable_amplitudes(
        lambdas, A, B, C, z, z_s, rho_1, rho_2, h_1,
        include_primary=False,
    )
    Phi_hom = _phi_from_stable_amplitudes(
        lambdas, A_h, B_h, C_h, z, z_s, rho_baseline, rho_baseline, h_1,
        include_primary=False,
    )
    w_phi = (
        Phi_lay - Phi_hom - _image_spectral_sum(
            lambdas, plan.coeffs, plan.dists,
        )
    ) * weights * lambdas
    # The residual primary term. Zero — bit-exactly — whenever the
    # caller follows the ADR-0007 recommendation and matches
    # ``rho_baseline`` to the resistivity of the source layer.
    d_rho = _primary_rho(z, z_s, rho_1, rho_2, h_1) - _primary_rho(
        z, z_s, rho_baseline, rho_baseline, h_1,
    )
    c = _log_grid_offset(z, z_s, h_1, d_rest=plan.d_rest)
    out = _hankel_contract_smooth(lambdas, s_values, w_phi, c=c)
    out = out + _image_real_space_sum(
        plan.coeffs, plan.dists, s_values, plan.lambda_clamp,
    )
    if d_rho == 0.0:
        return out
    return out + _primary_term_real_space(
        d_rho, s_values, z - z_s, plan.lambda_clamp,
    )


def two_layer_probe_matrix(
    probe_points: np.ndarray,     # (M, 3)
    source_points: np.ndarray,    # (N, 3)
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
    min_distance: float = 1e-3,
    lambda_max_factor: float = 200.0,
) -> np.ndarray:
    """Potential matrix ``phi = G @ I`` for arbitrary layer combinations.

    Returns the ``(M, N)`` matrix with ``G[m, n]`` = potential at
    ``probe_points[m]`` per unit current injected at
    ``source_points[n]``, evaluated with the full two-layer spectral
    kernel (:func:`two_layer_real_space_kernel`). Valid for **every**
    probe/source layer combination — upper–upper, cross-layer and
    lower–lower — unlike the Tagg/Sunde uu image series that the
    fast paths use (audit 2026-07-08, WP-D1: the uu series applied to
    layer-2 points was measured +7 % at z = 7 m and +25 % at z = 12 m
    for K = +0.818, h_1 = 5 m).

    Cost: one spectral-amplitude solve per (z, z_s) depth group plus a
    ``J0`` contraction (see "Cost control" below) — reserve for the
    sub-blocks that the uu series cannot handle.

    Notes
    -----
    The near-singularity is regularised like the image-series paths:
    the horizontal distance is clamped at ``min_distance`` whenever
    the vertical separation is below ``min_distance`` as well.

    Cost control: probe/source pairs are grouped by their (z, z_s)
    depth combination (rounded to 1 µm). Within a group the primary
    $1/R$ field is evaluated in closed form at every pair, and the
    *reflected* remainder — analytic in $t = \\ln(s + c)$ — is what the
    interpolation sees. Groups larger than
    :data:`_HANKEL_INTERP_THRESHOLD` pairs are sampled on a log-spaced
    ``s``-grid whose node count is derived from the group's dynamic
    range (:func:`_interp_node_count`) and interpolated with a cubic
    spline, keeping surface-grid evaluations tractable.

    Accuracy (review pass 9, finding F15)
    -------------------------------------
    The historic fixed 48-node linear interpolation of the *total*
    kernel was documented at "relative error ≲ 1e-4" but measured
    2.1e-3, because (a) the node count ignored the dynamic range of
    ``s`` and (b) the total kernel contains the $1/R$ primary term
    whose λ-truncated quadrature ripples in ``s`` with period
    $2\\pi/\\lambda_\\text{max}$ — a ripple no coarse interpolant can
    follow. With the primary term and the degenerate image terms in
    closed form and range-sized cubic nodes, the interpolated and the
    exact per-pair branch agree to **8e-7** relative (measured over
    surface, equal-depth-in-layer-2 and cross-layer probe/source
    combinations, 400 probes over a 90 m square), i.e. the documented
    1e-4 holds with two orders of margin — not the "four orders" and
    "~1e-8" that stood here at 0.15.0.dev, which were 2–3 orders
    optimistic and contradicted both the module header and
    ``docs/api/coupling.md``.
    """
    M = probe_points.shape[0]
    N = source_points.shape[0]
    if M and N:
        _validate_depths(
            float(np.min(probe_points[:, 2])),
            float(np.min(source_points[:, 2])),
            labels=("min(probe_points[:, 2])", "min(source_points[:, 2])"),
        )
    G = np.zeros((M, N), dtype=float)

    def _group_values(
        s_flat: np.ndarray, zm: float, zn: float,
    ) -> np.ndarray:
        """Vectorised kernel over many s at one (z, z_s) pair.

        The spectral amplitudes depend on (λ-grid, z, z_s) only, so
        they are solved **once per group** on a shared λ-grid built
        for the most demanding radius (λ_max from the smallest s,
        oscillation resolution and log-region cap from the largest);
        all s-values then reduce to one ``J0``-matrix contraction of
        the reflected part plus a closed-form primary term.
        """
        plan = _plan_truncation(
            z=zm, z_s=zn, rho_1=rho_1, rho_2=rho_2, h_1=h_1,
            rho_baseline=None, s_near=float(s_flat.min()),
            s_far=float(s_flat.max()),
            lambda_max_factor=lambda_max_factor,
            # 4 frames: _plan_truncation -> _group_values ->
            # two_layer_probe_matrix -> user.
            warn_stacklevel=4,
        )
        lambdas, weights = _hankel_lambda_grid(
            lambda_max=plan.lambda_max, char_length=plan.char_length,
            s=float(s_flat.max()), n_log=32, n_lin=96, warn_stacklevel=4,
        )
        A, B, _, C = _spectral_amplitudes(lambdas, zn, rho_1, rho_2, h_1)
        Phi_refl = _phi_from_stable_amplitudes(
            lambdas, A, B, C, zm, zn, rho_1, rho_2, h_1,
            include_primary=False,
        ) - _image_spectral_sum(lambdas, plan.coeffs, plan.dists)
        w_phi = Phi_refl * weights * lambdas
        c = _log_grid_offset(
            zm, zn, h_1, floor=min_distance, d_rest=plan.d_rest,
        )
        vals = _hankel_contract_smooth(lambdas, s_flat, w_phi, c=c)
        vals = vals + _image_real_space_sum(
            plan.coeffs, plan.dists, s_flat, plan.lambda_clamp,
        )
        rho_primary = _primary_rho(zm, zn, rho_1, rho_2, h_1)
        if rho_primary == 0.0:
            return vals
        return vals + _primary_term_real_space(
            rho_primary, s_flat, zm - zn, plan.lambda_clamp,
        )

    # Group by the (z, z_s) pair — the kernel then depends on s only.
    z_keys = np.round(probe_points[:, 2] / 1e-6).astype(np.int64)
    zs_keys = np.round(source_points[:, 2] / 1e-6).astype(np.int64)
    for zk in np.unique(z_keys):
        rows = np.where(z_keys == zk)[0]
        zm = float(probe_points[rows[0], 2])
        for zsk in np.unique(zs_keys):
            cols = np.where(zs_keys == zsk)[0]
            zn = float(source_points[cols[0], 2])
            dxy = (
                probe_points[rows][:, None, 0:2]
                - source_points[cols][None, :, 0:2]
            )
            s_grid = np.sqrt(np.einsum("mnk,mnk->mn", dxy, dxy))
            if abs(zm - zn) < min_distance:
                np.maximum(s_grid, min_distance, out=s_grid)
            vals = _group_values(s_grid.ravel(), zm, zn)
            G[np.ix_(rows, cols)] = vals.reshape(s_grid.shape)
    # Physical prefactor: phi = G_phys / (2π) per unit current (the
    # spectral kernel carries the rho/2 convention — see
    # solver/mom_sommerfeld.py for the bookkeeping).
    return G / (2.0 * math.pi)


def two_layer_layered_correction_real_space(
    s: float,
    z: float,
    z_s: float,
    *,
    rho_1: float,
    rho_2: float,
    h_1: float,
    rho_baseline: float | None = None,
    lambda_max_factor: float = 200.0,
    n_log: int = 32,
    n_lin: int = 96,
) -> float:
    """Real-space layered *correction* over the homogeneous-rho_1 baseline.

    Computes
    $$
    \\Delta G(s, z, z_s) \\;=\\;
        G_{\\text{2-layer}}(s, z, z_s; \\rho_1, \\rho_2, h_1)
        \\;-\\; G_{\\text{homog}}(s, z, z_s; \\rho_1)
    $$
    by subtracting the spectral kernels **before** the Hankel
    integration. The singular source term
    $\\rho_1/(2\\lambda)\\,e^{-\\lambda|z-z_s|}$ is identical in
    both spectral kernels and **cancels exactly**, leaving a
    smooth, exponentially decaying integrand. Two big advantages:

    1. In the homogeneous limit $\\rho_2 = \\rho_1$ the spectral
       difference is *identically zero* at every $\\lambda$, so the
       integrator returns 0 to machine precision (no spurious
       diagonal contribution from finite-Sommerfeld-quadrature
       error at $z = z_s$).
    2. The kernel difference $(a_1 - a_1^{\\text{hom}})e^{\\lambda z}
       + (b_1 - b_1^{\\text{hom}})e^{-\\lambda z}$ has no
       $1/(2\\lambda)$ piece, so the small-$\\lambda$ region is
       finite and easy to integrate.

    The caller adds this correction on top of the homogeneous
    potential computed with the existing
    :func:`groundfield.solver.image._self_corrected_kernel` (which
    correctly handles the line-self diagonal).

    The optional ``rho_baseline`` parameter selects which homog
    soil to subtract:

    - ``None`` (default): subtract homog with $\\rho_1$. Suitable
      when the calling solver builds $\\phi_\\text{hom}$ uniformly
      with $\\rho_1$.
    - explicit float: subtract homog with the given resistivity.
      Use ``rho_2`` for source segments in the lower layer when
      the calling solver matches its $\\phi_\\text{hom}$ baseline
      to the source layer (recommended for production-grade solver,
      ADR-0007 §"Phase A.1").

    Returns 0 in the homogeneous limit by construction; otherwise
    a finite real value with the same units as
    :func:`two_layer_real_space_kernel`.
    """
    if rho_baseline is None:
        rho_baseline = rho_1
    if abs(rho_2 - rho_1) < 1e-12 * max(rho_1, 1.0) and \
            abs(rho_baseline - rho_1) < 1e-12 * max(rho_1, 1.0):
        return 0.0

    _validate_depths(z, z_s)
    plan = _plan_truncation(
        z=z, z_s=z_s, rho_1=rho_1, rho_2=rho_2, h_1=h_1,
        rho_baseline=rho_baseline, s_near=s, s_far=s,
        lambda_max_factor=lambda_max_factor, warn_stacklevel=3,
    )
    lambdas, weights = _hankel_lambda_grid(
        lambda_max=plan.lambda_max, char_length=plan.char_length, s=s,
        n_log=n_log, n_lin=n_lin, warn_stacklevel=3,
    )

    # Layered amplitudes
    A, B, _, C = _spectral_amplitudes(
        lambdas, z_s, rho_1, rho_2, h_1,
    )
    # Baseline (homog) amplitudes — both layers at rho_baseline.
    A_h, B_h, _, C_h = _spectral_amplitudes(
        lambdas, z_s, rho_baseline, rho_baseline, h_1,
    )

    # Evaluate the *reflected* Phi for both and subtract. When the
    # source is in the same layer as the baseline-rho region, the
    # singular particular term cancels identically and the residual is
    # bounded. When the baseline differs from rho_at_source (e.g.,
    # rho_baseline=rho_2 with source in upper at z_s<h_1, where the
    # layered Phi has rho_1/(2λ)·exp() but the baseline-homog Phi has
    # rho_2/(2λ)·exp()), the residual carries a
    # (rho_at_source - rho_baseline)/(2R) divergence. That piece is
    # handled in closed form below rather than by quadrature — it is
    # the only non-decaying part of the spectral difference, so leaving
    # it in the integral produced an O((λ_max·R)^{-1/2}) ripple in s.
    # Callers should still select rho_baseline = rho at the source
    # layer (ADR-0007 §"Phase A.1"), which makes the term vanish.
    Phi_lay = _phi_from_stable_amplitudes(
        lambdas, A, B, C, z, z_s, rho_1, rho_2, h_1,
        include_primary=False,
    )
    Phi_hom = _phi_from_stable_amplitudes(
        lambdas, A_h, B_h, C_h, z, z_s, rho_baseline, rho_baseline, h_1,
        include_primary=False,
    )
    delta_Phi = Phi_lay - Phi_hom - _image_spectral_sum(
        lambdas, plan.coeffs, plan.dists,
    )

    integrand = delta_Phi * j0(lambdas * s) * lambdas
    total = float(np.sum(weights * integrand))
    total += float(
        _image_real_space_sum(plan.coeffs, plan.dists, s, plan.lambda_clamp)
    )

    d_rho = _primary_rho(z, z_s, rho_1, rho_2, h_1) - _primary_rho(
        z, z_s, rho_baseline, rho_baseline, h_1,
    )
    if d_rho == 0.0:
        return total
    return total + float(
        _primary_term_real_space(d_rho, s, z - z_s, plan.lambda_clamp)
    )
